# serverless.yml

service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  # userstableName: 'users-table-${self:provider.stage}'
  # sessionstableName: 'sessions-table-${self:provider.stage}'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
    usePipenv: true

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: eu-west-1
  # profile: ${opt:profile, 'default'}  # Use the 'serverless deploy --profile serverless_admin' or defaults to 'default'
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - dynamodb:Query
  #       - dynamodb:Scan
  #       - dynamodb:GetItem
  #       - dynamodb:PutItem
  #       - dynamodb:UpdateItem
  #       - dynamodb:DeleteItem
  #     Resource:
  #       - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
  #       - { "Fn::GetAtt": ["SessionsDynamoDBTable", "Arn" ] }
  # environment:
  #   USERS_TABLE: ${self:custom.userstableName}
  #   SESSION_TABLE: ${self:custom.sessionstableName}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# resources:
#   Resources:
#     UsersDynamoDBTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: phone_number
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: phone_number
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: ${self:custom.userstableName}
#     SessionsDynamoDBTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: userId
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: userId
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: ${self:custom.sessionstableName}

# package:
#   include:
#     - .venv/lib/python3.8/site-packages/pydantic/**
#     - .venv/lib/python3.8/site-packages/pydantic_core/**