# serverless.yml

service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  # userstableName: 'users-table-${self:provider.stage}'
  # sessionstableName: 'sessions-table-${self:provider.stage}'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
    usePipenv: true

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: eu-west-1
  environment:
    LANGCHAIN_ENDPOINT: ${env:LANGCHAIN_ENDPOINT}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
    TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
    SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
    BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
    TOKEN: ${{ secrets.TOKEN }}
    WHATSAPP_APP_ID: ${{ secrets.WHATSAPP_APP_ID }}
    WHATSAPP_APP_SECRET: ${{ secrets.WHATSAPP_APP_SECRET }}
    WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
    WHATSAPP_RECIPIENT_WAID: ${{ secrets.WHATSAPP_RECIPIENT_WAID }}
    WHATSAPP_PHONE_NUMBER_ID: ${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
    WHATSAPP_VERSION: ${{ secrets.WHATSAPP_VERSION }}
    WHATSAPP_VERIFY_TOKEN: ${{ secrets.WHATSAPP_VERIFY_TOKEN }}
    LANGCHAIN_TRACING_V2: ${{ variables.LANGCHAIN_TRACING_V2 }}
    LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
    LANGCHAIN_PROJECT: ${{ secrets.LANGCHAIN_PROJECT }}
    LANGCHAIN_ENDPOINT: ${{ variables.LANGCHAIN_ENDPOINT }}
    # USERS_TABLE: ${self:custom.userstableName}
    # SESSION_TABLE: ${self:custom.sessionstableName}
  # profile: ${opt:profile, 'default'}  # Use the 'serverless deploy --profile serverless_admin' or defaults to 'default'
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - dynamodb:Query
  #       - dynamodb:Scan
  #       - dynamodb:GetItem
  #       - dynamodb:PutItem
  #       - dynamodb:UpdateItem
  #       - dynamodb:DeleteItem
  #     Resource:
  #       - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
  #       - { "Fn::GetAtt": ["SessionsDynamoDBTable", "Arn" ] }

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# resources:
#   Resources:
#     UsersDynamoDBTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: phone_number
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: phone_number
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: ${self:custom.userstableName}
#     SessionsDynamoDBTable:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: userId
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: userId
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: ${self:custom.sessionstableName}

# package:
#   include:
#     - .venv/lib/python3.8/site-packages/pydantic/**
#     - .venv/lib/python3.8/site-packages/pydantic_core/**