name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the workflow in a Linux environment

    steps:
    - uses: actions/checkout@v4  # Checks-out the repository

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Set to the target Python version

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --deploy --dev
        npm install -g serverless
        npm install serverless-python-requirements

    - name: Deploy with Serverless
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-1'
      run: |
        serverless deploy
