name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the workflow in a Linux environment

    steps:
    - uses: actions/checkout@v4  # Checks-out the repository

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Set to the target Python version

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --deploy --dev
        npm install -g serverless
        npm install serverless-python-requirements

    - name: Deploy with Serverless
      env:
        IS_OFFLINE: false
        AWS_DEFAULT_REGION: 'eu-west-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
        TOKEN: ${{ secrets.TOKEN }}
        WHATSAPP_APP_ID: ${{ secrets.WHATSAPP_APP_ID }}
        WHATSAPP_APP_SECRET: ${{ secrets.WHATSAPP_APP_SECRET }}
        WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
        WHATSAPP_RECIPIENT_WAID: ${{ secrets.WHATSAPP_RECIPIENT_WAID }}
        WHATSAPP_PHONE_NUMBER_ID: ${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
        WHATSAPP_VERSION: ${{ env.WHATSAPP_VERSION }}
        WHATSAPP_VERIFY_TOKEN: ${{ secrets.WHATSAPP_VERIFY_TOKEN }}
        LANGCHAIN_TRACING_V2: ${{ env.LANGCHAIN_TRACING_V2 }}
        LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
        LANGCHAIN_PROJECT: ${{ secrets.LANGCHAIN_PROJECT }}
        LANGCHAIN_ENDPOINT: ${{ env.LANGCHAIN_ENDPOINT }}
      run: |
        serverless deploy
